# M2 reproducibility check

Generated by `scripts/validate_m2_release.py`. This check reads published receipts and does not replace `homology-8b9005e2d9-s42`.

## Frozen baseline on main

Data version `gvpa-recognition-c7f6f005d717`: 2078 candidates, 2076 QC-eligible, 1721 primary, 478 clusters, discovery 1453/335, validation 623/143, cluster leakage false.

## B branch `feature/m2-1-data-reproduction`

Counts, output hashes, and the split-manifest hash match the frozen baseline. Cluster leakage is false.

## C branch `analysis/10-pf00741-hmm-mapping`

PDB 7R1C chain N maps to PF00741.24 with 39 match states: 88 deposited residues, 65 modeled, 23 unmodeled.

## Notes

- B did not check gv.zip SHA-256; the recognition JSON hash matches the frozen audit.
- B MMseqs2 is '18.8cc5c'; frozen receipt is 15-6f452. Cluster TSV hashes differ and the reproduced split version is not the frozen version. Counts and split manifest hash match.

## Errors

- None.

## MMseqs2 threshold sensitivity

Coverage is 0.8. The frozen split was not replaced.

| Setting | Identity | Clusters | Max cluster | Singletons | Split agreement |
| --- | ---: | ---: | ---: | ---: | ---: |
| relaxed | 0.7 | 140 | 306 | 53 | 0.591522 |
| main | 0.8 | 478 | 104 | 228 | 1.0 |
| strict | 0.9 | 1220 | 27 | 822 | 0.596339 |
